# site settings
title: S.C.D. Fanese
subtitle:
email: scfanese@gmail.com
description: Società Ciclistica Dilettantistica Fanese
baseurl: "/"
url: # the base hostname & protocol for your site
author: SCD Fanese
street_address: Via Metauro - c/o Stadio R.Mancini
city: Fano
state: PU
zip_code: 61032

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

socials:
  Instagram: https://www.instagram.com/scdfanese/
  Facebook: https://www.facebook.com/scdfanese/
  Strava: https://www.strava.com/clubs/106034

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
